<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>E-Mail</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $tr = '';
            foreach ($this->view->posts as $val) {
                $tr .= "<tr>";
                $tr .= "<td>{$val->id}</td>";
                $tr .= "<td>{$val->nome}</td>";
                $tr .= "<td>{$val->email}</td>";
                $tr .= "</tr>";
            }
            echo $tr;
            ?>
        </tbody>
    </table>
</div>
