<div class="col-12">
    <div class="well well-sm alert-info">
        <form action="/post/store" method="post" accept-charset="utf-8">
            <div class="form-group ">
                <label for="idade">Id:</label>
                <input type="text" class="form-control" id="id" name="id">
            </div>
            <div class="form-group ">
                <label for="nome">Nome:</label>
                <input type="text" class="form-control" id="nome" name="nome">
            </div>
            <div class="form-group ">
                <label for="email">E-Mail</label>
                <input type="text" class="form-control" id="email" name="email">
            </div>
            <div class="text-right form-group">
                <button class="btn btn-primary">Post</button>
                <a href="/posts" class="btn btn-default">Cancelar</a>
            </div>
        </form>
    </div>
</div>