<div class="col-12">
    <?php if (isset($this->view->result)) { ?>
        <?php if ($this->view->result == true) { ?>
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4>Alert!</h4>
                <strong>Sucesso!</strong> Contato salvo.
            </div>
        <?php } else { ?>
            <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4>Alert!</h4>
                <strong>Erro!</strong> Contato não salvo.
            </div>
    <?php
        }
    }
    ?>
</div>
<div class="col-4 col-sm-4">
    <div class="well well-sm alert-info">
    <div class="form-group ">
            <label for="idade">Id:</label>
            <input type="text" class="form-control" id="id">
        </div>
        <div class="form-group ">
            <label for="nome">Nome:</label>
            <input type="text" class="form-control" id="nome">
        </div>
        <div class="form-group ">
            <label for="email">E-Mail</label>
            <input type="text" class="form-control" id="email">
        </div>
        <div class="text-right form-group">
            <button class="btn btn-primary">Post</button>
            <a href="/post/create" class="btn btn-default">Create</a>
        </div>
    </div>
</div>
<div class="col-8 col-sm-8">
    <div class="well well-sm" style="background-color: #FFF !important;">
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nome</th>
                        <th>E-Mail</th>
                    </tr>
                </thead>
                <tbody class="tbody-posts">
                    <?php
                    $tr = '';
                    foreach ($this->view->posts as $val) {
                        $tr .= "<tr class=\"tr-posts\" id=\"{$val->id}\">";
                        $tr .= "<td>{$val->id}</td>";
                        $tr .= "<td><a href=\"/post/{$val->id}/show\">{$val->nome}</a></td>";
                        $tr .= "<td>{$val->email}</td>";
                        $tr .= "</tr>";
                    }
                    echo $tr;
                    ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
