<div class="col-lg-4 col-sm-4">
    <div class="well well-sm alert-info">
        <form action="/post/store" method="post" accept-charset="utf-8">
            <div class="form-group ">
                <label for="nome">Nome:</label>
                <input type="text" class="form-control input-sm" id="nome" name="nome"
                       value="<?php echo (isset($this->view->post->nome)) ? $this->view->post->nome : ''; ?>">
            </div>
            <div class="form-group ">
                <label for="email">E-Mail</label>
                <input type="text" class="form-control input-sm" id="email" name="email"
                       value="<?php echo (isset($this->view->post->email)) ? $this->view->post->nome : ''; ?>">
            </div>
            <div class="text-right form-group">
                <button class="btn btn-xs btn-success">Save</button>
                <a href="/post/create" class="btn btn-xs btn-default"><i class="glyphicon glyphicon-plus"></i>&nbsp;&nbsp;Create</a>
            </div>
        </form>
    </div>
    <?php
    if ($this->renderView('alerts/_success')) {
        $this->renderView('alerts/_success');
    }
    ?>
    <?php
    if ($this->renderView('alerts/_errors')) {
        $this->renderView('alerts/_errors');
    }
    ?>
</div>

<div class="col-lg-8 col-sm-8">
    <div class="well well-sm" style="background-color: #FFF !important;">
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Nome</th>
                    <th>E-Mail</th>
                    <th>Opções</th>
                </tr>
                </thead>
                <tbody class="tbody-posts">
                <?php
                $tr = '';
                foreach ($this->view->posts as $val) {
                    $tr .= "<tr class=\"tr-posts\" id=\"{$val->id}\">";
                    $tr .= "<td>{$val->id}</td>";
                    $tr .= "<td><a href=\"/post/{$val->id}/show\">{$val->nome}</a></td>";
                    $tr .= "<td>{$val->email}</td>";
                    $tr .= "<td class=\"alert-info\"><a class=\"btn btn-xs btn-warning\" href=\"/post/{$val->id}/edit\"><i class=\"glyphicon glyphicon-edit\"></i>&nbsp;&nbsp;Edit</a>&nbsp;<a class=\"btn btn-xs btn-danger\" href=\"/post/{$val->id}/delete\" onclick=\"return confirm('Deseja deletar esse contato?')\"><i class=\"glyphicon glyphicon-trash\"></i>&nbsp;&nbsp;Delete</a></td>";
                    $tr .= "</tr>";
                }
                echo $tr;
                ?>
                </tbody>
            </table>
        </div>
    </div>
</div>