<div class="col-12">
	<table class="table table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>E-Mail</th>
            </tr>
        </thead>
        <tbody class="tbody-posts">
            <td><?php echo $this->view->post->id; ?></td>
            <td><?php echo $this->view->post->nome; ?></td>
            <td><?php echo $this->view->post->email; ?></td>
        </tbody>
    </table>
</div>