<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php $this->getPageTitle('|'); ?>Micro Framework</title>
    <link href="<?php $this->getCSS(); ?>" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="collapsed navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-9" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span
                        class="icon-bar"></span><span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand">Micro Framework</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-9">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="/">Home</a>
                </li>
                <li>
                    <a href="/listar">Listar</a>
                </li>
                <li>
                    <a href="/posts">Posts</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <?php echo $this->content(); ?>
        </div>
    </div>
</div>

<?php $this->getJS(); ?>
<script type="text/javascript">
    $(document).ready(function () {
        $("table thead tr th:nth-child(2)").addClass('hidden-sm hidden-xs');
        $("table tbody tr td:nth-child(2)").addClass('hidden-sm hidden-xs');
        /*$(document).on("click", ".tbody-posts .tr-posts", function() {
         var idPost = $(this).attr('id');
         var url = 'Ajax/PostsController.php';
         var dados_post = 'acao=show' + '&id=' + idPost;
         $.ajax({
         url: url,
         type: 'POST',
         data: dados_post,
         dataType: 'json',
         beforeSend: function() {

         },
         success: function(data) {
         console.log(data);
         $.each(data.dados, function(i, val) {
         $('#id').val(data.dados[i].id);
         $('#nome').val(data.dados[i].nome);
         $('#email').val(data.dados[i].email);
         });
         },
         error: function(data) {
         console.log(data);
         $('#id').val('Erro! Contate o Administrador do Sistemas.');
         $('#nome').val('Erro! Contate o Administrador do Sistemas.');
         $('#email').val('Erro! Contate o Administrador do Sistemas.');
         }
         });
         });*/
    });
</script>
</body>
</html>
